### ISSUE TITLE
Unable to get docker image

### ISSUE THREAD

**Issue by ashishyeri** [sigven/pcgr#125] opened 2021-02-16 22:10 UTC
Hi Sigven,

Thank you very much for your package. I'm trying to install pcgr to use it with the docker image on my Linux machine, but run into following issue. I've attached my docker info too here. This might be a naive question, but would greatly appreciate any help. 

Best regards,

Ashish

$docker pull sigven/pcgr:0.9.0rc
0.9.0rc: Pulling from sigven/pcgr
5c939e3a4d10: Pull complete 
c63719cdbe7a: Pull complete 
19a861ea6baf: Pull complete 
651c9d2d6c4f: Pull complete 
ed31f0fdac58: Pull complete 
059b9a354f0b: Pull complete 
c864b0d69669: Pull complete 
9e780bbb67a6: Pull complete 
a8dcf1638611: Pull complete 
70cd2ecdf468: Pull complete 
fcd5422c87c2: Extracting [==================================================>]  1.531MB/1.531MB
7f089c6df976: Download complete 
6071493fa412: Download complete 
e9b2dc0077bc: Download complete 
45b02e96861e: Download complete 
00bf39545d82: Download complete 
236b4046ed7d: Download complete 
f79fa6664c54: Download complete 
40f40f374412: Download complete 
98941f2a89e3: Download complete 
4a58869e7379: Download complete 
c30641ee269a: Download complete 
3d1c82d3056c: Download complete 
451075fc3483: Download complete 
8a008ecd5a70: Download complete 
eba760864612: Download complete 
935cb7830925: Download complete 
a9ecab06668a: Download complete 
fbda930c4e6f: Download complete 
ad597e445484: Download complete 
a3da9132cbb9: Download complete 
165a9fbedf57: Download complete 
25be7e8b81c0: Download complete 
de50e9f8f8b5: Download complete 
6027cde0d380: Download complete 
84d0d9556116: Download complete 
32df73f89a58: Download complete 
2bb0e07e40ea: Download complete 
111ab86f979b: Download complete 
4d62f1b3ef84: Download complete 
dd999535790d: Download complete 
1211ba518614: Download complete 
6d2394cc75e3: Download complete 
b1c62dd3c535: Download complete 
df41f07bb3be: Download complete 
c1ce7e654966: Download complete 
4dd7295197b0: Download complete 
7d193331ddb1: Download complete 
f5541aa2a4a7: Download complete 
8a3f06bad98d: Download complete 
f031cc57160d: Download complete 
f867da6a5a35: Download complete 
c4492f544341: Download complete 
aee5722ee2a9: Download complete 
3c4181e92951: Download complete 
7f73e2256368: Download complete 
8a23e407d26b: Download complete 
95e01e493176: Download complete 
1f9315e39c14: Download complete 
fe42902204c2: Download complete 
190150017643: Download complete 
02b5dc8f857c: Download complete 
de0b579a3be4: Download complete 
e5c414901834: Download complete 
0ed405295c30: Download complete 
86c2e92d4db3: Download complete 
b0c917202cac: Download complete 
c53feb9da113: Download complete 
738466d0ccc9: Download complete 
d6941a583fa1: Download complete 
8970679b5dc7: Download complete 
5238ce11f3fc: Download complete 
a7323f5623e1: Download complete 
failed to register layer: Error processing tar file(exit status 1): lchown /opt/vep/src/ensembl-vep/modules/LICENSE: invalid argument

I've also attached my docker info here:
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 20.10.3
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: none
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  rootless
 Kernel Version: 5.4.0-1037-aws
 Operating System: Ubuntu 18.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 64
 Total Memory: 251.9GiB
 Name: ip-10-50-1-41
 ID: WGHU:6R7E:2QSQ:2BVX:JEBV:M7SD:PQIA:ZV74:XLD5:5XUB:5REH:FWVW
 Docker Root Dir: /rawData/docker-tmp
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

**Comment by sigven** [comment] 2021-02-16 22:28
Hi Ashish,

Currently, I seem unable to reproduce your error. Do you get the same error when pulling the latest release (0.9.1)?

regards,
Sigve

**Comment by ashishyeri** [comment] 2021-02-16 22:37
Thanks for your prompt reply Sigev. Yes I get the same error from 0.9.1. 
failed to register layer: Error processing tar file(exit status 1): lchown /opt/vep/src/ensembl-vep/modules/LICENSE: invalid argument

**Comment by sigven** [comment] 2021-02-16 22:43
I suspect this is an issue with your local Docker installation, although I am not sure. At the moment I am not sure what can be the cause for your error. Personally, I am able to pull the images without any errors.

**Comment by ashishyeri** [comment] 2021-02-16 23:46
Hi Sigev,
I suspect it is to do with the memory and cpus Docker is trying to use. In your installation instructions, you say "Adjust the computing resources dedicated to the Docker". How would I do that on my Linux system?Thanks again!

Regards,

Ashish

**Comment by sigven** [comment] 2021-02-19 12:20
I am afraid I am not an expert on that matter, I suggest you consult some Docker documentation resources. Otherwise, you could try to install the Conda-based workflow. Closing the issue for now.

regards,
Sigve

**Closed by sigven** 2021-02-19 12:20 UTC
