### ISSUE TITLE
Error while running-  subprocess.CalledProcessError: Command 'docker images -q sigven/pcgr:0.7.0' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by vipuljain123** [sigven/pcgr#75] opened 2019-05-03 12:38 UTC
vipul@bioinfo-08:/bioinfo-data/Vipul/DATA/CnS/pcgr$ python /opt/installers/pcgr-0.7.0/pcgr.py --input_vcf /opt/installers/pcgr-0.7.0/examples/tumor_sample.COAD.vcf.gz --input_cna /opt/installers/pcgr-0.7.0/examples/tumor_sample.COAD.cna.tsv /opt/installers/pcgr-0.7.0 /opt/installers/pcgr-0.7.0/examples grch37 /opt/installers/pcgr-0.7.0/examples/pcgr_conf.COAD.toml tumor_sample.COAD
Traceback (most recent call last):
  File "/opt/installers/pcgr-0.7.0/pcgr.py", line 564, in <module>
    if __name__=="__main__": __main__()
  File "/opt/installers/pcgr-0.7.0/pcgr.py", line 49, in __main__
    output = subprocess.check_output(str(check_docker_command), stderr=subprocess.STDOUT, shell=True)
  File "/home/vipul/anaconda3/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/home/vipul/anaconda3/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'docker images -q sigven/pcgr:0.7.0' returned non-zero exit status 1.

**Comment by sigven** [comment] 2019-05-03 12:46
Have you checked that Docker is up and running?

**Comment by vipuljain123** [comment] 2019-05-03 13:34
Hi,

Yes its installed properly. What are the options to check further?


Thanks & Regards,

Vipul Todarwal
Bioinformatician,
Datar Cancer Genetics Limited,
Nashik (India).

Mob. +919822434003

**Comment by sigven** [comment] 2019-05-03 13:37
What is listed when you write `docker images`? And which version of Docker are you using?

**Comment by vipuljain123** [comment] 2019-05-03 13:50
Got permission denied while trying to connect to the Docker daemon socket
at unix:///var/run/docker.sock: Get
http://%2Fvar%2Frun%2Fdocker.sock/v1.39/images/json:
dial unix /var/run/docker.sock: connect: permission denied



Thanks & Regards,

Vipul Todarwal
Bioinformatician,
Datar Cancer Genetics Limited,
Nashik (India).

Mob. +919822434003

**Comment by sigven** [comment] 2019-05-03 13:53
Hi,

Then the issue is on your side, related to the Docker installation, and not related to PCGR software. Make sure your Docker installation works fine before you start using PCGR. Closing the issue.

regards,
Sigve

**Closed by sigven** 2019-05-03 13:53 UTC
