### ISSUE TITLE
hg38 and PROTEIN_DOMAIN

### ISSUE THREAD

**Issue by vladsaveliev** [sigven/pcgr#116] opened 2020-08-13 04:43 UTC
Hi Sigve,

I noticed that between 0.8.0 and 0.8.4, PROTEIN_DOMAIN field disappeared from the tables in the HTML report. I played a bit with different versions and input data, and narrowed it down to this: for the most recent PCGR (dockerized), PROTEIN_DOMAIN is generated for GRCh37 test data that you provide (e.g. COAD), but if I liftover the VCF to hg38 and try PCGR against hg38, PROTEIN_DOMAIN will not show up.

So wondering if you would be able to take a look at this, and also probably replace one of your test examples with a hg38 version, just to cover more use cases?

[tumor_sample.COAD.hg38.vcf.gz](https://github.com/sigven/pcgr/files/5067120/tumor_sample.COAD.hg38.vcf.gz)

Vlad

**Comment by sigven** [comment] 2020-08-17 08:37
Hi Vlad,

Thanks for the notification, I seem to recall that the Pfam cross-reference (which comes from VEP) altered it's naming convention some time ago, that might be the cause. I believe it is working well in the development version I am working on getting out soon (0.9.0, for both hg19 and hg38). I agree having more use cases for both assemblies would be a good idea, I am on it!

best,
Sigve

**Comment by sigven** [comment] 2020-09-24 08:45
Fixed in 0.9.0rc

**Closed by sigven** 2020-09-24 08:45 UTC
