### ISSUE TITLE
Inconsistency in the division into tiers

### ISSUE THREAD

**Issue by przemekl** [sigven/pcgr#61] opened 2018-11-09 07:28 UTC
The same variant has been classified into two tiers (1 & 2), two lines appear in the 'global variant bowser'.
Unfortunately, the variant is only shown in tier 2 table.

**Comment by sigven** [comment] 2018-11-09 08:03
Hi,thanks! Again, I think sharing your VCF with me is the quickest way for me to find the bug.

**Comment by przemekl** [comment] 2018-11-09 08:30
The problem appears for the variant:
chr17   43082434        rs41293455      G       A       284     PASS    TYPE=SNV;TDP=574;VD=282;TVAF=0.4913;BIAS=2:2;REFBIAS=102:189;VARBIAS=99:183;PMEAN=36.8;PSTD=1;QUAL=35;QSTD=1;SBF=1;ODDRATIO=1.00241;MQ=60;SN=55.4;HIAF=0.4911;ADJAF=0;SHIFT3=0;MSI=1;MSILEN=1;NM=1.1;HICNT=277;HICOV=564;LSEQ=TGTGCTTTGTTCTGGATTTC;RSEQ=CAGGTCCTCAAGGGCAGAAG
grch38, I use parameters TDP and TVAF

**Comment by sigven** [comment] 2018-11-09 12:21
Hi,
I am struggling to reproduce this. Variant you are referring to is a rare BRCA1 stop-gain variant (of germline origin). 

[https://www.ncbi.nlm.nih.gov/projects/SNP/snp_ref.cgi?rs=rs41293455](https://www.ncbi.nlm.nih.gov/projects/SNP/snp_ref.cgi?rs=rs41293455)


In tumor-only runs it may thus be excluded when setting `exclude_dbsnp_nonclinical = true` (only *somatic* variants of clinical relevance in ClinVar/DoCM are kept during this filtering step, and this criteria is not fulfilled by this variant). 

Either way, how this variant ended up with duplicate entries in the browser and in two tiers still appear as a mystery to me. I would need the full VCF, and your toml file to reproduce it.

regards,
Sigve

**Comment by przemekl** [comment] 2018-11-09 19:36
Please, run pcgr with attached toml file.
[pcgr_test.toml.txt](https://github.com/sigven/pcgr/files/2567275/pcgr_test.toml.txt)

**Comment by sigven** [comment] 2018-11-09 20:29
And the VCF, please.

**Comment by sigven** [comment] 2018-11-09 21:30
Reproduced it now, investigating the cause. Getting back to you soon.
regards

**Comment by sigven** [comment] 2018-11-10 07:57
Should be fixed now in dev now.

**Closed by sigven** 2018-11-10 07:57 UTC
